spring.application.name=demo

# PayPal Configuration
paypal.client-id=
paypal.client-secret=
paypal.base-url=https://api-m.sandbox.paypal.com

# Stripe Configuration
# Replace with your Stripe credentials
stripe.secret.key=WKoM0....
stripe.publishable.key=KJMyj....
stripe.webhook.secret=whsec_...

# Stripe Checkout Redirect URLs
stripe.success.url=http://localhost:8080/api/payments/stripe/success
stripe.cancel.url=http://localhost:8080/api/payments/stripe/cancel
