spring.application.name=demo
paypal.client-id=AdihajHIKmCexUybp6F2T8amzFHq3pXW9WwHkk6PZypFhRSSjO6hD2d2OBr56Uo1AY_LdlUVvvvMUV4h
paypal.client-secret=EKbsMIoVbLveXi1w4Z7QOEDT5pRU3PtXHzaftPbru9P_VYB99Y7UsLYrZL_9s1Qoz3J2ucZ1_JBvYe14
paypal.base-url=https://api-m.sandbox.paypal.com