spring.application.name=demo

# PayPal Configuration
paypal.client-id=
paypal.client-secret=
paypal.base-url=https://api-m.sandbox.paypal.com

# Stripe Configuration
# Replace with your Stripe credentials
stripe.secret.key=KoM0....
stripe.publishable.key=TKJMyj....
stripe.webhook.secret=whsec_...
